### ISSUE TITLE
More than one PiHole

### ISSUE THREAD

**Issue by sml156** [jboughton/ManHole#1]
I run two piholes right now, any thoughts of being able to add another pihole to your interface settings.

OHH and by the way this is pretty cool, thanks

**Comment by jboughton** [comment]
I'm glad you like it! Support for multiple 'holes isn't out of the question, but is not a feature I intend to add until everything is working flawlessly.

There's a lot of logic to work out, and for the time being I only run a single Pi-hole on my network, which will make testing difficult. When the time comes, I'll fire up an Ubuntu server VM and tinker around.
