### ISSUE TITLE
Disabling & Freezing

### ISSUE THREAD

**Issue by Cryptic-Soldier** [jboughton/ManHole#3]
So starting it up, you have to manually 'enable' pihole from the application.

Clicking 'Manual Refresh' 'Disables' Pihole causing the user to have to re-enable it.

Once re-enabled for a 2nd time, clicking 'Manual Refresh' again causing the entire program to freeze up and needing to be 'End Task' from Task Manager.

**Comment by p1r473** [comment]
I had this same thing happen

**Comment by jboughton** [comment]
Sorry you're having issues, but this was just a personal fun project that I haven't touched in years, and I don't even code anymore. You'll have to patch it yourself, or find an alternative software. Sorry.
